name: Releasing APK files
inputs:
  github_token:
    description: "GitHub Token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate release info
      shell: bash
      run: |
        echo "
        **Change log** :point_down:
        [Revanced](https://github.com/revanced/revanced-patches/releases)
        [Revanced Extended](https://github.com/inotia00/revanced-patches/releases)
        "> ${{ github.workspace }}-CHANGELOG.txt

    - name: Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: |
          ./release/*.apk
        name: ${{ env.APP_NAME }}-${{ env.VARIANT }}-${{ env.APP_VERSION }}-${{ env.patch_version }}
        token: ${{ inputs.github_token }}
        tag: ${{ env.APP_NAME }}-${{ env.VARIANT }}-${{ env.APP_VERSION }}-${{ env.patch_version }}
        bodyFile: ${{ github.workspace }}-CHANGELOG.txt
        allowUpdates: true
